include_guard()
include(cmakepp_lang/cmakepp_lang)

list(APPEND _cmaize_Toolchain_autopopulated_variable_names "CMAKE_C_COMPILER")
list(APPEND _cmaize_Toolchain_autopopulated_variable_names "CMAKE_CXX_COMPILER")

#[[[
# The Toolchain class is a source code representation of the toolchain file
# that can be provided by users to specify options sent to every dependency.
# 
# Users need a way to specify options which should be passed to every 
# dependency. By convention this is done by setting the options in a 
# toolchain file. The Toolchain class is the source code representation of 
# this file and provides CMaize a way to interact with the toolchain file 
# the user provided. Two sets of values will be in the Toolchain instance: 
# those set by the user in the actual file, and those CMaize autopopulates 
# (autopopulated variables will be things like the compiler which we 
# explicitly pass to ensure consistent builds).
#]]
cpp_class(Toolchain)
    
    ## Map of options automatically populated
    cpp_attr(Toolchain auto_options)

    ## Contents of the user-provided toolchain file. These take higher
    ## priority than those automatically populated by CMaize. This should
    ## be treated as immutable once the values are read into it.
    cpp_attr(Toolchain encoded_toolchain_contents)

    #[[[
    # Default constructor for Toolchain object with only autopopulated
    # options available.
    #]]
    cpp_constructor(CTOR Toolchain)
    function("${CTOR}" self)

        # Initialize the toolchain object
        Toolchain(__initialize "${self}")

        # Store toolchain contents
        Toolchain(SET "${self}" encoded_toolchain_contents "")

    endfunction()

    #[[[
    # Constructor for Toolchain object with a path to a toolchain file.
    #
    # :param toolchain_path: Path to the toolchain file to load.
    # :type toolchain_path: path
    #]]
    cpp_constructor(CTOR Toolchain path)
    function("${CTOR}" self toolchain_path)

        cpp_file_exists(toolchain_exists "${toolchain_path}")
        if(NOT "${toolchain_exists}")
            cpp_raise(FileNotFound "Provided toolchain file does not exist. "
                                   "Toolchain provided: ${toolchain_path}")
        endif()

        # Initialize the toolchain object
        Toolchain(__initialize "${self}")

        # Read the toolchain file
        file(READ "${toolchain_path}" file_contents)

        # Store toolchain contents
        cpp_encode_special_chars("${file_contents}" encoded_file_contents)
        Toolchain(SET "${self}" encoded_toolchain_contents "${encoded_file_contents}")

    endfunction()

    #[[[
    # Constructor for Toolchain object with a string assumed to be the
    # contents of an already opened toolchain file.
    #
    # :param file_contents: Contents of the toolchain file.
    # :type file_contents: str
    #]]
    cpp_constructor(CTOR Toolchain str)
    function("${CTOR}" self file_contents)

        # Initialize the toolchain object
        Toolchain(__initialize "${self}")

        # Store toolchain contents
        cpp_encode_special_chars("${file_contents}" encoded_file_contents)
        Toolchain(SET "${self}" encoded_toolchain_contents "${encoded_file_contents}")

    endfunction()

    cpp_member(generate_file_contents Toolchain str)
    function("${generate_file_contents}" self return_value)

        # Initialize the file contents with a warning
        set(file_string
            "# This file was generated by CMaize. Any changes made to this"
            "# file will be overwritten the next time it is generated.\n\n"
        )

        # Get the autopopulated options
        Toolchain(GET "${self}" auto_opt_map auto_options)
        cpp_map(KEYS "${auto_opt_map}" keys)

        # Start the autopopulated section
        string(APPEND file_string "# CMaize Autopopulated Options\n\n")

        # Add the autopopulated options
        foreach(key ${keys})
            cpp_map(GET "${auto_opt_map}" value "${key}")
            string(APPEND file_string "set(${key} ${value})\n")
        endforeach()

        # Start the user toolchain section
        string(APPEND file_string "\n# User Toolchain\n\n")

        # Add the user toolchain
        Toolchain(GET "${self}" file_contents encoded_toolchain_contents)
        string(APPEND file_string "${file_contents}")

        cpp_decode_special_chars("${file_string}" file_string)

        set("${return_value}" "${file_string}" PARENT_SCOPE)

    endfunction()

    cpp_member(write_toolchain Toolchain path)
    function("${write_toolchain}" self toolchain_path)

        # Generate the toolchain contents
        Toolchain(generate_file_contents "${self}" file_contents)

        # Write the contents to the specified file
        file(WRITE "${toolchain_path}" "${file_contents}")

    endfunction()

    # [[[
    # Autopopulates certain toolchain variables as default values to be used
    # if not specified by the user toolchain file.
    # ]]
    cpp_member(_autopopulate_options Toolchain)
    function("${_autopopulate_options}" self)

        # Get the autopopulated map
        Toolchain(GET "${self}" auto_opt_map auto_options)

        # Autopopulate some values from the CMake environment
        foreach(var_name ${_cmaize_Toolchain_autopopulated_variable_names})
            cpp_map(SET "${auto_opt_map}" "${var_name}" "${${var_name}}")
        endforeach()

    endfunction()

    #[[[
    # Initialize empty option maps of the Toolchain object.
    #]]
    cpp_member(__initialize Toolchain)
    function("${__initialize}" self)

        # Set the auto-populated map to an empty map
        cpp_map(CTOR auto_opt_map)
        Toolchain(SET "${self}" auto_options "${auto_opt_map}")

        # Autopopulate some options
        Toolchain(_autopopulate_options "${self}")

    endfunction()

cpp_end_class()
