include_guard()
include(build_recipe/build_with_cmake/build_with_cmake)
include(build_recipe/build_with_module/build_with_module)

function(_cpp_BuildRecipe_build_dependency _cBbd_handle _cBbd_install)
    _cpp_Object_has_base(${_cBbd_handle} _cBbd_is_cmake BuildWithCMake)
    _cpp_Object_has_base(${_cBbd_handle} _cBbd_is_module BuildWithModule)
    if(_cBbd_is_cmake)
        _cpp_BuildWithCMake_build_dependency(${_cBbd_handle} ${_cBbd_install})
    elseif()
        _cpp_BuildWithModule_build_dependency(${_cBbd_handle} ${_cBbd_install})
    else()
        _cpp_error("Must override member build_dependency.")
    endif()
endfunction()
