include_guard()

function(_cpp_FindRecipe_find_dependency _cFfd_handle _cFfd_hints)
    _cpp_Object_get_value(${_cFfd_handle} _cFfd_version version)
    _cpp_are_not_equal(_cFfd_version_set "${_cFfd_version}" "latest")
    if(_cFfd_version_set)
        set(_cFfd_version "VERSION ${_cFfd_version}")
    else()
        set(_cFfd_version "")
    endif()
    _cpp_Object_get_value(${_cFfd_handle} _cFfd_comps components)
    _cpp_is_not_empty(_cFfd_has_comps _cFfd_comps)
    if(_cFfd_has_comps)
        set(_cFfd_comps "COMPONENTS ${_cFfd_comps}")
    else()
        set(_cFfd_comps "")
    endif()

endfunction()
