include_guard()
include(cmakepp_lang/cmakepp_lang)

#[[[
# Comment stating that the file was generated by CMaize. Usually this should
# be added at the top of the file.
#
# :param _cgbc_message: Return variable with the message.
# :type _cgbc_message: desc
#
# :returns: CMake comment stating that the file was generated by CMaize.
# :rtype: desc
#]]
function(_cmaize_generated_by_cmaize __cgbc_message)

    set(
        "${__cgbc_message}"
        "# This file is generated by CMaize.
# 
# NOTE: Any modifications made in this file may be lost the next time
#       CMake is run."
)

    cpp_return("${__cgbc_message}")

endfunction()
