include_guard()
include(kwargs/kwarg_value)
include(kwargs/set_kwarg)
include(logic/is_empty)

function(_cpp_Kwargs_set_default _cKsd_handle _cKsd_kwarg _cKsd_value)
    _cpp_Kwargs_kwarg_value(${_cKsd_handle} _cKsd_temp ${_cKsd_kwarg})
    _cpp_is_empty(_cKsd_empty _cKsd_temp)
    if(_cKsd_empty)
        _cpp_Kwargs_set_kwarg(${_cKsd_handle} ${_cKsd_kwarg} "${_cKsd_value}")
    endif()
    _cpp_Kwargs_kwarg_value(${_cKsd_handle} _cKsd_temp ${_cKsd_kwarg})
endfunction()
