name: CMaize Unit Tests

on:
  pull_request:
    branches:
      - master

  # Allows manual triggering with the "Run workflow" button
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # [minimum version, last 3.x, latest stable, latest release candidate]
        cmake: [3.19.7, 3.31.9, latest, latestrc]

    env:
      cmake_version: ${{ matrix.cmake }}
      os: linux-x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ env.cmake_version }}

      - name: Configure Project
        run: |
          cmake -H. -Bbuild -DBUILD_TESTING=ON

      - name: Unit Tests
        run: |
          cd build
          ctest \
              j 2 \
              --output-on-failure \
              -LE integration_tests
